apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-k8-scg
spec:
  title: K8 Spring Cloud Gateway
  description: An interactive workshop on Kubernetes Spring Cloud Gateway
  url: https://github.com/samarsinghal/lab-k8-scg
  content:
    image: samarsinghal/tanzu_env:latest
#     image: harbor.tanzu.frankcarta.com/workshop/tkg_workshop:latest
#     image: docker.io/samarsinghal/tkg_workshop:latest
    files: github.com/samarsinghal/lab-k8-scg
  vendor: eduk8s.io
  difficulty: intermediate
  duration: 100m
  tags:
  - containers
  session:
    namespaces:
      budget: xx-large
    applications:
      terminal:
        enabled: true
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
