apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tas4ops
spec:
  title: TAS Operator workshop
  description: An interactive workshop on TAS operations
  url: https://github.com/samarsinghal/tas4ops-workshop-eduk8s.git
  content:
    image: docker.io/samarsinghal/tas4ops-workshop:latest
    files: github.com/samarsinghal/tas4ops-workshop-eduk8s
  vendor: eduk8s.io
  difficulty: intermediate
  duration: 60m
  tags:
  - containers
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
